---
- name: install collectd zookeeper plugin
  sudo: yes
  copy:
    src: zookeeper-collectd-plugin.py
    dest: /usr/share/collectd/plugins/zookeeper.py
    mode: 0444
  tags:
    - zookeeper
    - collectd

- name: configure collectd zookeeper plugin
  sudo: yes
  template:
    src: zookeeper-collectd-plugin.conf.j2
    dest: /etc/collectd.d/zookeeper.conf
  notify:
    - restart collectd
  tags:
    - zookeeper
    - collectd
