---
- name: install netcat
  sudo: yes
  yum:
    name: nmap-ncat
    state: present
  tags:
    - zookeeper

- name: install wait script
  sudo: yes
  copy:
    src: zookeeper-wait-for-listen.sh
    dest: /usr/local/bin
    mode: u=rwx,g=rx,o=rx
  tags:
    - zookeeper

- name: generate default env file
  sudo: yes
  template:
    src: zookeeper-env.j2 
    dest: "/etc/default/{{ zookeeper_service }}"
  notify: 
    - restart zookeeper
  tags: 
    - zookeeper

- name: generate systemd service file 
  sudo: yes
  template:
    src: zookeeper-service.j2 
    dest: "/usr/lib/systemd/system/{{ zookeeper_service }}.service"
  notify: 
    - register zookeeper service
    - reload systemd daemon 
  tags: 
    - zookeeper

- meta: flush_handlers
