---
- name: create zookeeper acl 
  sudo: yes 
  shell: "{{ marathon_zk_acl_cmd }}" 
  notify:
    - restart marathon
  when: zk_marathon_user_secret is defined
  run_once: true
  tags:
    - marathon
   
- name: create marathon conf directory
  sudo: yes
  file:
    dest: /etc/marathon/conf
    state: directory
  tags:
    - marathon

- include: framework_auth.yml

- name: set key/value options
  sudo: yes
  when: item.value != ""
  copy:
    dest: /etc/marathon/conf/{{ item.key }}
    content: "{{ item.value }}"
  with_items:
    - key: zk
      value: "{{ marathon_zk_connect }}"
    - key: ssl_keystore_password
      value: "{{ marathon_keystore_password }}"
    - key: http_port
      value: 18080
  notify:
    - restart marathon
  tags:
    - marathon

- name: check keystore consistency
  fail: msg="cannot set keystore path without keystore password"
  when: marathon_keystore_path != "" and marathon_keystore_password == ""

- name: copy ssl keystore
  when: marathon_keystore_path != ""
  sudo: yes
  copy:
    src: "{{ marathon_keystore_path }}"
    dest: /etc/marathon/keystore.jks
  notify:
    - restart marathon
  tags:
    - marathon

- name: create marathon_keystore_path
  when: marathon_keystore_path != ""
  sudo: yes
  copy:
    dest: /etc/marathon/conf/ssl_keystore_path
    content: /etc/marathon/keystore.jks
  notify:
    - restart marathon
  tags:
    - marathon

# since the Mesosphere Marathon package configures itself with files
# in a directory, we need to clean up old options when they become
# unset.
- name: remove blank options
  sudo: yes
  when: item.value == ""
  file:
    dest: /etc/marathon/conf/{{ item.key }}
    state: absent
    mode: 0700
  with_items:
    - key: http_credentials
      value: "{{ marathon_http_credentials }}"
    - key: ssl_keystore_password
      value: "{{ marathon_keystore_password }}"
    - key: ssl_keystore_path
      value: "{{ marathon_keystore_path }}"
  notify:
    - restart marathon
  tags:
    - marathon

- name: remove ssl keystore
  when: marathon_keystore_path == ""
  sudo: yes
  file:
    dest: /etc/marathon/keystore.jks
    state: absent
  tags:
    - marathon
      
