---
# some created directories may be redundant, but are kept in case anything else
# changes, and to enable the picking and choosing of components/roles.
- name: create consul configuration directory
  sudo: yes
  file:
    path: /etc/consul
    state: directory
    mode: 0770
  tags:
    - consul
    - distributive

- name: create symlink to distributive consul checklist
  sudo: yes
  file:
    state: link
    src: /usr/share/distributive/consul.json
    dest: /etc/distributive.d/consul.json
  tags:
    - consul
    - distributive

- name: register distributive tests with consul
  sudo: yes
  copy:
    src: distributive-consul-config.json
    dest: /etc/consul
  when: "'{{ consul_servers_group}}' in group_names"
  notify:
    - reload consul
  tags:
    - consul
    - distributive

- name: run distributive consul test
  sudo: yes
  command: /usr/bin/distributive -f /etc/distributive.d/consul.json -d "" --verbosity="warn"
  tags:
    - consul
    - distributive
