---
- name: deploy nginx template
  sudo: yes
  template:
    src: consul.nginx.j2
    dest: /etc/consul/consul.nginx
  tags:
    - consul

- name: deploy nginx service
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: nginx-consul.service.j2
      dest: /usr/lib/systemd/system/nginx-consul.service
    - src: nginx-consul.env.j2
      dest: /etc/default/nginx-consul.env
  notify:
    - restart nginx-consul
  tags:
    - consul

- name: install nginx template
  sudo: yes
  run_once: yes
  command: consul-cli kv-write --token={{ consul_acl_secure_token }} secure/service/nginx/templates/consul @/etc/consul/consul.nginx
  tags:
    - consul

- name: install nginx admin password
  sudo: yes
  run_once: yes
  command: consul-cli kv-write --token={{ consul_acl_secure_token }} secure/service/nginx/auth/users/admin '{{ nginx_admin_password_encrypted }}'
  when: nginx_admin_password_encrypted is defined
  tags:
    - consul

- name: enable nginx-consul
  sudo: yes
  service:
    name: nginx-consul
    enabled: yes
    state: started
  notify:
    - restart nginx-consul
  tags:
    - consul
