---
# Passed to Consul via Registrator for service discovery
zookeeper_service: zookeeper
zookeeper_service_tags: "{{ zookeeper_service }}"
zookeeper_ensemble: mantl
zookeeper_container_name: "{{ zookeeper_service }}"
zookeeper_data_volume: "{{ zookeeper_service }}-data-volume"
zookeeper_log_threshold: WARN

# Allow larger than default maximum client connections.
zookeeper_max_conns: 200

# The number of milliseconds of each tick
zookeeper_tick_time: 2000

# The number of ticks that the initial
# synchronization phase can take
zookeeper_init_limit: 100

# The number of ticks that can pass between
# sending a request and getting an acknowledgement
zookeeper_sync_limit: 5

# the port at which the clients will connect
zookeeper_client_port: 2181
zookeeper_server_ports: 2888:3888

zookeeper_os_user: zookeeper

# Set the ZooKeeper ID
zookeeper_server_group: role=control
zookeeper_id: "
  {%- if zk_id is defined -%}
    {{ zk_id }}
  {%- else -%}
    {%- for host in groups[zookeeper_server_group]|sort -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        {{ loop.index }}
      {%- endif -%}
    {%- endfor -%}
  {%- endif -%}
"
