---
zookeeper_image: asteris/zookeeper
zookeeper_image_tag: latest
zookeeper_ports: "-p 2181:2181 -p 2888:2888 -p 3888:3888"
zookeeper_env: "/etc/default/{{ zookeeper_service }}"

# Passed to Consul via Registrator for service discovery
zookeeper_service: zookeeper
zookeeper_service_tags: "{{ zookeeper_service }}"
zookeeper_ensemble: cluster1
zookeeper_container_name: "{{ zookeeper_service }}"
zookeeper_data_volume: "{{ zookeeper_service }}-data-volume"

# Set the ZooKeeper ID
zookeeper_server_group: zookeeper_servers
zookeeper_id: "
  {%- if zk_id is defined -%}
    {{ zk_id }}
  {%- else -%}
    {%- for host in groups[zookeeper_server_group] -%}
      {%- if host == 'default' or host == inventory_hostname or host == ansible_fqdn or host in ansible_all_ipv4_addresses -%}
        {{ loop.index }}
      {%- endif -%}
    {%- endfor -%}
  {%- endif -%}
"
