apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: "{{ kube_hyperkube_image }}:{{ kube_version }}"
    command:
    - /hyperkube
    - apiserver

    # Network binding & advertising
    - --bind-address={{ private_ipv4 }}
    - --secure-port={{ kube_master_port }}
    - --insecure-bind-address=127.0.0.1
    - --insecure-port={{ kube_insecure_port }}
    - --advertise-address={{ ansible_default_ipv4.address }}
    - --service-cluster-ip-range={{ kube_service_addresses }}

    # Security
    - --allow-privileged=true
    - --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
    - --basic-auth-file={{ kube_users_dir }}/known_users.csv
    - --client-ca-file=/etc/pki/CA/ca.cert
    - --kubelet-certificate-authority=/etc/pki/CA/ca.cert
    - --kubelet-client-certificate={{ host_cert }}
    - --kubelet-client-key={{ host_key }}
    - --tls-cert-file={{ host_cert }}
    - --tls-private-key-file={{ host_key }}
    - --service-account-key-file={{ host_key }}

    # Other
    - --etcd-servers=http://127.0.0.1:8500
    - --runtime-config=extensions/v1beta1/daemonsets=true
    {% if enable_cloud_provider | bool -%}
    - --cloud-provider={{ cloud_provider }}
    {% endif -%}
    - --v={{kube_log_level}}
    - --storage-backend=consul
    ports:
    - containerPort: {{ kube_master_port }}
      hostPort: {{ kube_master_port }}
      protocol: TCP
      name: https
    - containerPort: {{ kube_insecure_port }}
      hostPort: {{ kube_insecure_port }}
      protocol: TCP
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: etc-kubernetes
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
  volumes:
  - name: etc-kubernetes
    hostPath:
      path: /etc/kubernetes
  - name: etc-pki
    hostPath:
      path: /etc/pki
