---
- name: reload unit files
  sudo: yes
  command: systemctl daemon-reload

- name: restart mesos leader
  sudo: yes
  command: systemctl restart mesos-master

- name: remove mesos follower metadata
  sudo: yes
  command: "{{ item }}"
  with_items:
    - systemctl stop mesos-agent
    - rm -rf /tmp/mesos/meta/slaves/latest
    - systemctl start mesos-agent

- name: restart mesos follower
  sudo: yes
  command: systemctl restart mesos-agent

- name: restart nginx-mesos-leader
  sudo: yes
  command: systemctl restart nginx-mesos-leader

- name: reload nginx-mesos-leader
  sudo: yes
  command: systemctl daemon-reload

- name: restart collectd
  sudo: yes
  service:
    name: collectd
    state: restarted
