---
- name: create volume for brick
  sudo: yes
  lvol:
    vg: "{{ volume_group_name }}"
    lv: "{{ glusterfs_brick_volume_name }}"
    size:  100%FREE
  tags:
    - glusterfs
    - disk

- name: format brick volume
  sudo: yes
  filesystem:
    dev: "{{ glusterfs_brick_device }}"
    fstype: xfs
    opts: "-i size=512"
  tags:
    - glusterfs
    - disk

- name: create mount point for brick volume
  sudo: yes
  file:
    state: directory
    name: "{{ glusterfs_brick_mount }}"
    recurse: yes
    mode: 0755
  tags:
    - glusterfs
    - disk

- name: mount brick disk
  sudo: yes
  mount:
    state: mounted
    name: "{{ glusterfs_brick_mount }}"
    fstype: xfs
    src: "{{ glusterfs_brick_device }}"
    dump: 1
    passno: 2
  tags:
    - glusterfs
    - disk

- name: ensure brick location is present
  sudo: yes
  file:
    state: directory
    path: "{{ glusterfs_brick_location }}"
  tags:
    - glusterfs

- name: install server packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - glusterfs-cli
    - glusterfs-server
  notify:
    - reload glusterfs
  tags:
    - glusterfs

- name: start services
  sudo: yes
  command: systemctl start {{ item }}
  with_items:
    - glusterd
    - glusterfsd
  tags:
    - glusterfs

- name: probe servers
  run_once: true
  sudo: yes
  command: gluster peer probe {{ item }}.node.{{ consul_dns_domain }}
  with_items: groups[glusterfs_server_group]
  tags:
    - glusterfs

- name: create gluster_volume script
  sudo: yes
  template:
    src: gluster_volume.sh.j2
    dest: /etc/glusterfs/gluster_volume.sh
    mode: 755
  tags:
    - glusterfs

- name: create container volume
  run_once: true
  sudo: yes
  command: /etc/glusterfs/gluster_volume.sh {{ glusterfs_container_data_name }}
  tags:
    - glusterfs

- name: start container volume
  sudo: yes
  run_once: true
  gluster_volume:
    name: "{{ glusterfs_container_data_name }}"
    state: started
  tags:
    - glusterfs

- name: create consul service
  sudo: yes
  template:
    src: glusterfs.json.j2
    dest: /etc/consul/glusterfs.json
  notify:
    - reload consul
  tags:
    - glusterfs

- meta: flush_handlers
