---
- name: create directory structure for logstash
  sudo: yes
  file:
    path: "{{ logstash_conf_host }}"
    state: directory
    mode: 0755
  tags:
    - logging

- name: prepare config for logstash container
  sudo: yes
  template:
    src: logstash.conf.j2
    dest: "{{ logstash_conf_host }}/logstash.conf"
  notify:
    - restart logstash
  tags:
    - logging

- name: generate systemd service file
  sudo: yes
  template:
    src: logstash-service.j2
    dest: "/usr/lib/systemd/system/{{ logstash_service }}.service"
  notify:
    - reload systemd daemon
    - enable and start logstash
  tags:
    - logging

- meta: flush_handlers
