---
- name: reload systemd daemon
  sudo: yes
  command: systemctl daemon-reload
  tags: 
    - zookeeper 

- name: register zookeeper service
  sudo: yes 
  service:  
    enabled: yes 
    name: "{{ zookeeper_service }}"  
    state: started 
  tags:  
    - zookeeper  

- name: restart zookeeper
  sudo: yes
  service:
    name: "{{ zookeeper_service }}"
    state: restarted
  notify:
    - wait for zookeeper to listen
  tags:
    - zookeeper

- name: wait for zookeeper to listen
  command: /usr/local/bin/zookeeper-wait-for-listen.sh
