---
- name: install vault
  sudo: yes
  yum:
    name: "{{ vault_package }}"
    state: present
  tags:
    - vault
    - bootstrap

- name: configure vault
  sudo: yes
  template:
    src: vault.hcl.j2
    dest: /etc/vault/vault.hcl
  tags:
    - vault

- name: enable vault
  sudo: yes
  service:
    name: vault
    enabled: yes
    state: started
  tags:
    - vault

- name: wait for vault port
  wait_for:
    port: 8200
  tags:
    - vault

- include: bootstrap.yml
