---
glusterfs_version: 3.7.3
glusterfs_minor_version: 3.7
glusterfs_repo_sha256sum: 990b1a5f09f5ca555b2d7b94825d896a84d15bd0db2c085cb8f6259215e1d91a

glusterfs_mode: client
glusterfs_replication: "{{ groups[glusterfs_server_group] | count }}"
glusterfs_server_group: role=control

# brick storage
glusterfs_brick_mount: /mnt/glusterfs
glusterfs_brick_volume_group: "{{ volume_group_name }}"
glusterfs_brick_volume_name: glusterfs
glusterfs_brick_device: "/dev/{{ volume_group_name }}/{{ glusterfs_brick_volume_name }}"
glusterfs_volume_force: "{% if glusterfs_brick_device %}no{% else %}yes{% endif %}"
glusterfs_brick_location: "{% if glusterfs_brick_device %}{{ glusterfs_brick_mount }}{% else %}/etc/glusterfs/data{% endif %}"

# docker volume
glusterfs_container_data_name: container-volumes
glusterfs_container_data_mount: /mnt/{{ glusterfs_container_data_name }}
