---
- name: Monitoring | Influxdb | Write controller file
  sudo: yes
  copy:
    src: influxdb-grafana-controller.yaml
    dest: "{{ kube_manifest_dir }}/influxdb-grafana-controller.yaml"
  register: influxdb_rc_def
  when: enable_monitoring
  tags:
    - addons
    - monitoring

- name: Monitoring | Influxdb | Write service file
  sudo: yes
  copy:
    src: influxdb-service.yaml
    dest: "{{ kube_manifest_dir }}/influxdb-service.yaml"
  register: influxdb_svc_def
  when: enable_monitoring
  tags:
    - addons
    - monitoring

- name: Monitoring | Grafana | Write service file
  sudo: yes
  copy:
    src: grafana-service.yaml
    dest: "{{ kube_manifest_dir }}/grafana-service.yaml"
  register: grafana_svc_def
  when: enable_monitoring
  tags:
    - addons
    - monitoring

- name: Monitoring | Heapster | Write controller file
  sudo: yes
  copy:
    src: heapster-controller.yaml
    dest: "{{ kube_manifest_dir }}/heapster-controller.yaml"
  register: heapster_rc_def
  when: enable_monitoring
  tags:
    - addons
    - monitoring

- name: Monitoring | Heapster | Write service file
  sudo: yes
  copy:
    src: heapster-service.yaml
    dest: "{{ kube_manifest_dir }}/heapster-service.yaml"
  register: heapster_svc_def
  when: enable_monitoring
  tags:
    - addons
    - monitoring

- name: Monitoring | Influxdb | Create/update replication controller
  sudo: yes
  kube:
    namespace: kube-system
    resource: rc
    name: monitoring-influx-grafana-v1
    filename: "{{ kube_manifest_dir }}/influxdb-grafana-controller.yaml"
    state: "{{ influxdb_rc_def.changed | ternary('latest','present') }}"
    config: "{{ kube_config_dir }}/kubectl.kubeconfig"
  when: enable_monitoring
  delegate_to: "{{ groups[master_group_name][0] }}"
  run_once: true
  tags:
    - addons
    - monitoring

- name: Monitoring | Influxdb | Create/update service
  sudo: yes
  kube:
    namespace: kube-system
    resource: svc
    name: monitoring-influxdb
    filename: "{{ kube_manifest_dir }}/influxdb-service.yaml"
    state: "{{ influxdb_svc_def.changed | ternary('latest','present') }}"
    config: "{{ kube_config_dir }}/kubectl.kubeconfig"
  when: enable_monitoring
  delegate_to: "{{ groups[master_group_name][0] }}"
  run_once: true
  tags:
    - addons
    - monitoring

- name: Monitoring | Grafana | Create/update service
  sudo: yes
  kube:
    namespace: kube-system
    resource: svc
    name: monitoring-grafana
    filename: "{{ kube_manifest_dir }}/grafana-service.yaml"
    state: "{{ grafana_svc_def.changed | ternary('latest','present') }}"
    config: "{{ kube_config_dir }}/kubectl.kubeconfig"
  when: enable_monitoring
  delegate_to: "{{ groups[master_group_name][0] }}"
  run_once: true
  tags:
    - addons
    - monitoring

- name: Monitoring | Heapster | Create/update replication controller
  sudo: yes
  kube:
    namespace: kube-system
    resource: rc
    name: monitoring-heapster-v8
    filename: "{{ kube_manifest_dir }}/heapster-controller.yaml"
    state: "{{ heapster_rc_def.changed | ternary('latest','present') }}"
    config: "{{ kube_config_dir }}/kubectl.kubeconfig"
  when: enable_monitoring
  delegate_to: "{{ groups[master_group_name][0] }}"
  run_once: true
  tags:
    - addons
    - monitoring

- name: Monitoring | Heapster | Create/update service
  sudo: yes
  kube:
    namespace: kube-system
    resource: svc
    name: monitoring-heapster
    filename: "{{ kube_manifest_dir }}/heapster-service.yaml"
    state: "{{ heapster_svc_def.changed | ternary('latest','present') }}"
    config: "{{ kube_config_dir }}/kubectl.kubeconfig"
  when: enable_monitoring
  delegate_to: "{{ groups[master_group_name][0] }}"
  run_once: true
  tags:
    - addons
    - monitoring

