---
- name: reload vault
  sudo: yes
  command: systemctl reload vault
  notify:
    - wait for vault to listen

- name: reload sshd
  become: yes
  service:
    name: sshd
    state: reloaded

- name: restart vault
  sudo: yes
  command: systemctl restart vault
  notify:
    - wait for vault to listen

- name: wait for vault to listen
  wait_for:
    port: "{{ vault_default_port }}"
