---
# default is etc/utc in build 20141129 [http://cloud.centos.org/centos/7/images/]
- name: set timezone to etc/utc
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes

# add hosts to /etc/hosts
- name: configure hosts file
  sudo: yes
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
  tags:
    - common

- name: increase timeouts in YUM
  sudo: yes
  shell: "yum-config-manager --save --setopt {{ item.option }}={{ item.value }}"
  with_items:
    - option: timeout
      value: 60.0
    - option: retries
      value: 30

- name: enable EPEL repo
  sudo: yes
  yum:
    name: epel-release
    state: latest
  tags:
    - bootstrap

- name: install system utilities
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd-tools
    - nc
    - openssh
    - policycoreutils-python
    - unzip
    - jq
    - java-1.8.0-openjdk
  tags:
    - bootstrap

- name: disable firewalld
  sudo: yes
  service:
    name: firewalld
    enabled: false
    state: stopped
  register: command_result
  failed_when: "command_result|failed and 'No such file or directory' not in command_result.msg"

- name: install pip
  sudo: yes
  yum:
    name: python-pip
    state: latest

- name: update setuptools and pip
  sudo: yes
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - name: pip
    - name: setuptools

- name: disable requiretty in sudoers
  sudo: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ^.+requiretty$
    line: "# Defaults	requiretty"

- name: configure selinux
  sudo: yes
  selinux:
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_state }}"
  tags:
    - security
    - bootstrap

- name: enable yum repos
  sudo: yes
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
  with_items:
    - asteris-mantl-rpm.repo
    - ciscocloud-rpm.repo

- include: users.yml
- include: ssl.yml
- include: distributive.yml
- include: ssh.yml
- include: fail2ban.yml
