---
# default is etc/utc in build 20141129 [http://cloud.centos.org/centos/7/images/]
- name: set timezone to etc/utc
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes

# add hosts to /etc/hosts
- name: configure hosts file
  sudo: yes
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 644
  tags:
    - common

- name: install system utilities
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - httpd-tools
    - nc
    - openssh
    - policycoreutils-python
    - unzip
  tags:
    - bootstrap

- name: disable firewalld
  sudo: yes
  service:
    name: firewalld
    enabled: false
    state: stopped
  register: command_result
  failed_when: "command_result|failed and 'No such file or directory' not in command_result.msg"

- name: enable EPEL repo
  sudo: yes
  yum:
    name: epel-release
    state: latest

- name: install pip
  sudo: yes
  yum:
    name: python-pip
    state: latest

- name: update setuptools and pip
  sudo: yes
  pip:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - name: pip
    - name: setuptools

- name: install distributive
  sudo: yes
  yum:
    name: "https://bintray.com/artifact/download/ciscocloud/rpm/distributive-0.2.1-5.el7.centos.x86_64.rpm"
    state: present
  tags:
    - distributive

- name: disable requiretty in sudoers
  sudo: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ^.+requiretty$
    line: "# Defaults	requiretty"
  tags:

- name: configure selinux
  sudo: yes
  selinux:
    policy: "{{ selinux_policy }}"
    state: "{{ selinux_state }}"
  tags:
    - security
    - bootstrap

- include: users.yml
- include: ssl.yml
