apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: "{{ kube_hyperkube_image }}:{{ kube_version }}"
    command:
    - /hyperkube
    - proxy
    - --master=https://kubernetes.service.consul:{{ kube_master_port }}
    - --kubeconfig=/etc/kubernetes/kubeconfig.yml
    - --proxy-mode=iptables
    - --v={{ kube_log_level }}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: etc-kubernetes
      readOnly: true
    - mountPath: /etc/pki
      name: etc-pki
      readOnly: true
  volumes:
  - name: etc-kubernetes
    hostPath:
      path: /etc/kubernetes
  - name: etc-pki
    hostPath:
      path: /etc/pki
