---
- name: install packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - dnsmasq
    - bind-utils
    - NetworkManager
  tags:
    - dnsmasq
    - bootstrap

- name: ensure dnsmasq.d directory exists
  sudo: yes
  file:
    path: /etc/NetworkManager/dnsmasq.d
    state: directory
  tags:
    - dnsmasq

- name: configure dnsmasq for consul
  sudo: yes
  template:
    src: 10-consul
    dest: /etc/dnsmasq.d/10-consul
    mode: 755
  notify:
    - restart dnsmasq
  tags:
    - dnsmasq

- name: enable dnsmasq
  sudo: yes
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags:
    - dnsmasq

- name: configure networkmanager for dnsmasq
  sudo: yes
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    line: "dns=none"
    insertafter: "^\\[main\\]$"
  notify:
    - restart networkmanager
  tags:
    - dnsmasq

- name: add dnsmasq to /etc/resolv.conf
  sudo: yes
  lineinfile:
    dest: /etc/resolv.conf
    line: "search {{ consul_dns_domain }}\nnameserver 127.0.0.1"
    insertbefore: BOF
  tags:
    - dnsmasq

- meta: flush_handlers

- include: distributive.yml
