---
etcd_version: 2.2.5
etcd_client_port: 2379
etcd_peer_port: 2380

etcd_group_name: role=control

etcd_security: true

etcd_conf_dir: /etc/etcd
etcd_script_dir: /usr/libexec/etcd


etcd_initial_cluster_state: new
etcd_initial_cluster_token: etcd-k8-cluster

etcd_url_scheme: "http{% if etcd_security %}s{% endif %}"
etcd_initial_advertise_peer_urls: "{{ etcd_url_scheme }}://{{ inventory_hostname }}:{{ etcd_peer_port }}"
etcd_listen_peer_urls: "{{ etcd_url_scheme }}://0.0.0.0:{{ etcd_peer_port }}"
etcd_advertise_client_urls: "{{ etcd_url_scheme }}://{{ inventory_hostname }}:{{ etcd_client_port }}"
etcd_listen_client_urls: "{{ etcd_url_scheme }}://0.0.0.0:{{ etcd_client_port }}"

etcd_data_dir: /var/lib/etcd
