---
- name: install traefik
  sudo: yes
  yum:
    name: "{{ traefik_package }}"
    state: present
  tags:
    - traefik
    - bootstrap

- name: create directory for local traefik service override
  sudo: yes
  file:
    dest:  /etc/systemd/system/traefik.service.d
    state: directory
    mode: 0755
  tags:
    - traefik
    - bootstrap

- name: create local traefik service override
  sudo: yes
  copy:
    dest: /etc/systemd/system/traefik.service.d/marathon.conf
    content: |
      [Service]
      ExecStartPre=-/usr/bin/smlr {{ traefik_marathon_endpoint }}/v2/leader
  notify:
    - reload systemd
    - restart traefik
  tags:
    - traefik

- name: make certificate directory
  sudo: yes
  file:
    dest: /etc/traefik/certs
    state: directory
  tags:
    - traefik

- name: deploy certs
  sudo: yes
  copy:
    src: '{{ item }}'
    dest: /etc/traefik/certs/
  with_items:
    - ssl/certs/traefik-admin.cert.pem
    - ssl/private/traefik-admin.key.pem
  tags:
    - traefik

- name: configure traefik
  sudo: yes
  template:
    src: traefik.toml.j2
    dest: /etc/traefik/traefik.toml
    owner: traefik
    group: traefik
    mode: 0644
    backup: yes
  notify:
    - restart traefik
  tags:
    - traefik

- name: generate traefik consul service
  sudo: yes
  copy:
    src: 'traefik-consul.json'
    dest: '/etc/consul/traefik.json'
  notify:
    - reload consul
  tags:
    - traefik
