---
- name: write pod file
  sudo: yes
  copy:
    src: kube-ui-rc.yaml
    dest: "{{ kube_manifest_dir }}/kube-ui-rc.yaml"
  register: kube_ui_rc_def
  run_once: true
  tags:
    - addons
    - kube-ui
    - kubernetes

- name: write service file
  sudo: yes
  copy:
    src: kube-ui-svc.yaml
    dest: "{{ kube_manifest_dir }}/kube-ui-svc.yaml"
  register: kube_ui_svc_def
  run_once: true
  tags:
    - addons
    - kube-ui
    - kubernetes

- name: create or update replication controller
  sudo: yes
  kube:
    namespace: kube-system
    resource: rc
    name: kube-ui-v3
    filename: "{{ kube_manifest_dir }}/kube-ui-rc.yaml"
    state: "{{ kube_ui_rc_def.changed | ternary('latest','present') }}"
    server: "http://localhost:8085/"
  run_once: true
  tags:
    - addons
    - kube-ui
    - kubernetes

- name: create or update service
  sudo: yes
  kube:
    namespace: kube-system
    resource: svc
    name: kube-ui
    filename: "{{ kube_manifest_dir }}/kube-ui-svc.yaml"
    state: "{{ kube_ui_svc_def.changed | ternary('latest','present') }}"
    server: "http://localhost:8085/"
  run_once: true
  tags:
    - addons
    - kube-ui
    - kubernetes
