---
- name: write kibana pod file
  sudo: yes
  copy:
    src: kibana-rc.yaml
    dest: "{{ kube_manifest_dir }}/kibana-rc.yaml"
  register: kibana_rc_def
  run_once: true
  tags:
    - addons
    - logging
    - kubernetes

- name: write kibana service file
  sudo: yes
  copy:
    src: kibana-svc.yaml
    dest: "{{ kube_manifest_dir }}/kibana-svc.yaml"
  register: kibana_svc_def
  run_once: true
  tags:
    - addons
    - logging
    - kubernetes

- name: write elasticsearch pod file
  sudo: yes
  copy:
    src: es-rc.yaml
    dest: "{{ kube_manifest_dir }}/es-rc.yaml"
  register: es_rc_def
  run_once: true
  tags:
    - addons
    - logging
    - kubernetes

- name: write elasticsearch service file
  sudo: yes
  copy:
    src: es-svc.yaml
    dest: "{{ kube_manifest_dir }}/es-svc.yaml"
  register: es_svc_def
  run_once: true
  tags:
    - addons
    - logging
    - kubernetes

- name: create/update elasticsearch replication controller
  sudo: yes
  kube:
    namespace: kube-system
    resource: rc
    name: elasticsearch-logging-v1
    filename: "{{ kube_manifest_dir }}/es-rc.yaml"
    state: "{{ es_rc_def.changed | ternary('latest','present') }}"
    server: "http://localhost:8085/"
  run_once: true
  tags:
    - addons
    - logging
    - kubernetes

- name: create/update elasticsearch service
  sudo: yes
  kube:
    namespace: kube-system
    resource: svc
    name: elasticsearch-logging
    filename: "{{ kube_manifest_dir }}/es-svc.yaml"
    state: "{{ es_svc_def.changed | ternary('latest','present') }}"
    server: "http://localhost:8085/"
  run_once: true
  tags:
    - addons
    - logging
    - kubernetes

- name: create/update kibana replication controller
  sudo: yes
  kube:
    namespace: kube-system
    resource: rc
    name: kibana-logging-v1
    filename: "{{ kube_manifest_dir }}/kibana-rc.yaml"
    state: "{{ kibana_rc_def.changed | ternary('latest','present') }}"
    server: "http://localhost:8085/"
  run_once: true
  tags:
    - addons
    - logging
    - kubernetes

- name: create/update kibana service
  sudo: yes
  kube:
    namespace: kube-system
    resource: svc
    name: kibana-logging
    filename: "{{ kube_manifest_dir }}/kibana-svc.yaml"
    state: "{{ kibana_svc_def.changed | ternary('latest','present') }}"
    server: "http://localhost:8085/"
  run_once: true
  tags:
    - addons
    - logging
    - kubernetes
