---
- name: copy nginx configuration
  sudo: yes
  template:
    src: chronos.nginx.j2
    dest: /etc/chronos/chronos.nginx
  notify:
    - restart nginx-chronos
  tags:
    - chronos

- name: configure nginx
  sudo: yes
  command: consul-cli kv-write --token={{ consul_acl_secure_token }} secure/service/nginx/templates/chronos @/etc/chronos/chronos.nginx
  tags:
    - chronos

- name: configure nginx-chronos
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: nginx-chronos.service.j2
      dest: /usr/lib/systemd/system/nginx-chronos.service
    - src: nginx-chronos.env.j2
      dest: /etc/default/nginx-chronos.env
  notify:
    - reload nginx-chronos
    - restart nginx-chronos
  tags:
    - chronos

- name: enable nginx-chronos
  sudo: yes
  service:
    name: nginx-chronos
    enabled: yes
    state: started
  notify:
    - restart nginx-chronos
  tags:
    - chronos
