---
- hosts: all
  gather_facts: no
  connection: local
  vars:
    nova_compute_state: present
  tasks:
    - nova_compute:
        name: "{{ inventory_hostname }}"
        auth_url: "{{ os_auth_url }}"
        login_username: "{{ lookup('env', 'OS_USERNAME') }}"
        login_password: "{{ lookup('env', 'OS_PASSWORD') }}"
        login_tenant_name: "{{ os_tenant_name }}"
        key_name: "ansible_key"
        image_name: "{{ os_image_name }}"
        flavor_ram: "{{ os_flavor_ram }}"
        flavor_include: "{{ os_flavor_include }}"
        nics:
          - net-id: "{{ os_net_id }}"
        security_groups: default
        state: "{{ nova_compute_state }}"
      always_run: yes
      register: nova_compute_result
      tags: hosts

    - name: set ansible_ssh_host value to host private_ip
      set_fact: ansible_ssh_host={{ nova_compute_result.private_ip }}
      always_run: yes
      when: nova_compute_state == "present"
      tags: hosts

    - name: print host ip address
      debug: msg={{ ansible_ssh_host }}
      always_run: yes
      when: nova_compute_state == "present"
      tags: hosts

    - name: wait for host boot
      local_action:
        module: wait_for
        host: "{{ ansible_ssh_host }}"
        port: 22
        delay: "{{ boot_wait | default(60) }}"
        timeout: 120
        state: started
      always_run: yes
      when: nova_compute_result|changed and nova_compute_state == "present"
      tags: hosts
