---
- hosts: all
  serial: "{{ serial | default(1) }}"
  tasks:
    - include_vars: ../roles/consul/defaults/main.yml

    - name: install consul
      sudo: yes
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ consul_package }}"
        - "{{ consul_ui_package }}"

    - name: restart consul
      sudo: yes
      service:
        name: consul
        state: restarted
 
    - name: wait for leader
      command: /usr/local/bin/consul-wait-for-leader.sh

    - name: create secure acl
      sudo: yes
      run_once: yes
      command: consul-cli acl-update --token={{ consul_acl_master_token }} --name="Mantl Secure Token" --rule='key:secure:write' --rule='service::write' {{ consul_acl_secure_token }}
      tags:
        - consul
