---
# Workaround for https://github.com/CiscoCloud/mantl/161
- name: install latest device-mapper-libs
  sudo: yes
  yum:
    name: device-mapper-libs
    state: latest
  tags:
    - docker
    - bootstrap
    - lvm

- name: update lvg ansible module
  connection: local
  run_once: yes
  get_url:
    url: https://raw.githubusercontent.com/ansible/ansible-modules-extras/02b68be09dca9760a761d4147f76cfc940c41cba/system/lvg.py
    dest: "{{ playbook_dir }}/library/lvg.py"
  tags:
    - docker

- name: install LVM tools
  sudo: yes
  yum:
    name: lvm2
    state: latest
  tags:
    - docker
    - bootstrap
    - lvm

- name: list volume groups
  sudo: yes
  command: vgscan
  register: volume_groups
  tags:
    - docker
    - lvm

- name: Create volume group
  sudo: yes
  lvg:
    vg: "{{ lvm_volume_group_name }}"
    pvs: "{{ lvm_physical_device }}"
  when: volume_groups.stdout.find(lvm_volume_group_name) == -1
  tags:
    - docker
    - lvm

- name: enable lvmetad service
  sudo: yes
  service:
    name: lvm2-lvmetad
    enabled: yes
    state: started
  tags:
    - docker
    - lvm

- name: save volume group name as fact
  set_fact:  volume_group_name="{{ lvm_volume_group_name }}"
  tags:
    - lvm
